# Generated by Django 3.2.3 on 2021-06-09 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='from_user',
            field=models.ForeignKey(db_column='from_user', default=None, null=True, on_delete=django.db.models.expressions.Case, related_name='from_user', to=settings.AUTH_USER_MODEL, verbose_name='发送消息用户(空表示系统)'),
        ),
        migrations.AddField(
            model_name='message',
            name='to_user',
            field=models.ForeignKey(db_column='to_user', on_delete=django.db.models.expressions.Case, related_name='to_user', to=settings.AUTH_USER_MODEL, verbose_name='接收消息用户'),
        ),
    ]
