# Generated by Django 3.2.3 on 2021-06-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='have_read',
            field=models.BooleanField(default=False, verbose_name='是否已读'),
        ),
    ]
