# Generated by Django 3.2.3 on 2021-06-09 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competition', '0002_initial'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='member',
            field=models.ForeignKey(db_column='member', on_delete=django.db.models.expressions.Case, related_name='member', to=settings.AUTH_USER_MODEL, verbose_name='组员'),
        ),
        migrations.AddField(
            model_name='initialisegroup',
            name='competition',
            field=models.ForeignKey(db_column='competition', on_delete=django.db.models.expressions.Case, related_name='competition', to='competition.competitioninfo', verbose_name='比赛'),
        ),
        migrations.AddField(
            model_name='initialisegroup',
            name='initiator',
            field=models.ForeignKey(db_column='initiator', on_delete=django.db.models.expressions.Case, related_name='initiator', to=settings.AUTH_USER_MODEL, verbose_name='发起人'),
        ),
    ]
