# Generated by Django 3.2.3 on 2021-06-09 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_user',
            field=models.ForeignKey(db_column='appointment_user', on_delete=django.db.models.expressions.Case, related_name='appointment_user', to=settings.AUTH_USER_MODEL, verbose_name='预约人'),
        ),
    ]
