# Generated by Django 3.2.3 on 2021-06-09 13:33

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('en_name', models.CharField(max_length=64, verbose_name='英文名')),
                ('image', models.CharField(max_length=256, verbose_name='图片')),
                ('describe', models.CharField(max_length=2048, verbose_name='描述')),
            ],
            options={
                'verbose_name': '比赛分类',
                'verbose_name_plural': '比赛分类',
            },
        ),
        migrations.CreateModel(
            name='CompetitionCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('delete_time', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('host', models.CharField(max_length=32, verbose_name='主办方')),
                ('deliver_date', models.CharField(max_length=20, null=True, verbose_name='发布时间')),
                ('image', models.CharField(default=None, max_length=256, null=True, verbose_name='图片')),
                ('describe', models.CharField(default=None, max_length=2048, null=True, verbose_name='描述')),
                ('content', models.TextField(verbose_name='内容')),
                ('visit', models.IntegerField(default=0, verbose_name='浏览量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(db_column='category', default=None, null=True, on_delete=django.db.models.expressions.Case, related_name='category', to='competition.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '比赛信息',
                'verbose_name_plural': '比赛信息',
            },
        ),
    ]
