# Generated by Django 3.2.3 on 2021-06-09 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competitioncollection',
            name='c_collect_user',
            field=models.ForeignKey(db_column='c_collect_user', on_delete=django.db.models.expressions.Case, related_name='c_collect_user', to=settings.AUTH_USER_MODEL, verbose_name='收藏人'),
        ),
        migrations.AddField(
            model_name='competitioncollection',
            name='competition',
            field=models.ForeignKey(db_column='competitioninfo', on_delete=django.db.models.expressions.Case, related_name='competitioninfo', to='competition.competitioninfo', verbose_name='活动'),
        ),
    ]
